### ISSUE TITLE
Date filtering for activities not included

### ISSUE THREAD

**Issue by xandhen** [girgen/ss12000v2#107]
The `activities` endpoint does not have the `startDate.*` and `endDate.*` parameters to allow the caller to specify the time period during which the requested activities should be active.

This endpoint should have the same filtering capabilities as the `persons`, `duties` and `groups` endpoints to allow easy fetching of activities for an organisation or user.

The file `activities` endpoint in the paths/activities.yaml file should have the following parameters added.

```
      - name: startDate.onOrBefore
        description: |
          Begränsa urvalet till grupper som har ett startDate värde innan eller på det angivna datumet (RFC 3339-format, t.ex. "2016-10-15").
        in: query
        schema:
          type: string
          format: date
      - name: startDate.onOrAfter
        description: |
          Begränsa urvalet till grupper som har ett startDate värde på eller efter det angivna datumet (RFC 3339-format, t.ex. "2016-10-15").
        in: query
        schema:
          type: string
          format: date
      - name: endDate.onOrBefore
        description: |
          Begränsa urvalet till grupper som har ett endDate värde innan eller på det angivna datumet (RFC 3339-format, t.ex. "2016-10-15"). 
          Poster med ett endDate som ej är satt, tas alltid med.
        in: query
        schema:
          type: string
          format: date
      - name: endDate.onOrAfter
        description: |
          Begränsa urvalet till grupper som har ett endDate värde på eller efter det angivna datumet (RFC 3339-format, t.ex. "2016-10-15"). 
          Poster med ett endDate som ej är satt, tas alltid med.
        in: query
        schema:
          type: string
          format: date
```
