### ISSUE TITLE
Olika sätt att referera till andra objekt i listor , studentMemberships vs teachers

### ISSUE THREAD

**Issue by girgen** [girgen/ss12000v2#53]
Jag hittade en diskrepans. I modellen är StudendGroups.studentMemberships samma slags modell som Activity.DuryAssignment, men de är lite olika implementerade. Jag tycker att allOf som i studentmemberships är mest "rätt". Samtidigt är där en bug i openapi-generator/swagger-codegen så i så fall får jag inte inte ut start- och enddate till Java, men det är väl inte vårt problem...

```yaml
    studentMemberships:
      description: >
        Studentmedlemskap anger att en student är medlem i en grupp
        och vilken tidsperiod medlemskapet omfattar.
      type: array
      items:
        type: object
        allOf:
          - $ref: "common.yaml#/PersonReference"
          - type: object
            title: StudentMembership
            properties:
              startDate:

```

```yaml
    teachers:
      type: array
      items:
        type: object
        title: DutyAssignment
        properties:
          duty:
            $ref: "common.yaml#/DutyReference"
          startDate:
```

Resultet i exempelgenereringen från MS Code's OpenAPI Preview:

```json
      "studentMemberships": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "displayName": "string",
          "startDate": "2019-08-29",
          "endDate": "2019-08-29"
        }
      ],
```

resp

```json
      "teachers": [
        {
          "duty": {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "displayName": "string"
          },
          "startDate": "2019-08-29",
          "endDate": "2019-08-29",
          "minutesPlanned": 0
        }
      ],
```
